CREATE TABLE IF NOT EXISTS Data_R_Project_Mastodon_Log.log_local
ON CLUSTER statground_cluster
(
    uuid UUID COMMENT 'Log event UUID generated by GitHub Actions crawler',
    created_at Nullable(DateTime64(3, 'Asia/Seoul')) COMMENT 'Crawler log timestamp in Asia/Seoul',
    created_log Nullable(JSON) COMMENT 'Pipeline stage/config/count/error payload',
    language_code LowCardinality(String) DEFAULT 'en' COMMENT 'BCP-47 language code associated with crawler log/source rows; Mastodon source is en',
    created_at_key DateTime64(3, 'Asia/Seoul') MATERIALIZED coalesce(created_at, now64(3, 'Asia/Seoul'))
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/Data_R_Project_Mastodon_Log/log_local', '{replica}')
ORDER BY (created_at_key, uuid)
SETTINGS index_granularity = 8192
COMMENT 'Mastodon crawler pipeline log local replicated table; source language en';
