CREATE TABLE IF NOT EXISTS Data_R_Project_Mastodon_Raw.raw_local
ON CLUSTER statground_cluster
(
    uuid UUID COMMENT 'Stable Mastodon status UUID generated from instance/account/status_id; shared with Korean board rows',
    event_uuid UUID COMMENT 'UUID v7 Kafka event identifier generated by GitHub Actions crawler; ClickHouse UUID type',
    source LowCardinality(String) COMMENT 'Producer source such as github_actions',
    host LowCardinality(String) COMMENT 'Producer host such as GitHub runner name or self-hosted runner hostname',
    uuid_user Nullable(UUID) COMMENT 'Optional Statground user UUID v7; NULL for scheduled crawler events',
    ip IPv6 COMMENT 'Producer/client IP normalized to IPv6; missing values use ::',
    url String COMMENT 'Primary source URL for the event, normally Mastodon status URL',
    event_type LowCardinality(String) COMMENT 'Kafka event type; expected webr.mastodon.raw.v1 for raw Mastodon status snapshots',

    instance_host LowCardinality(String) COMMENT 'Mastodon instance host, e.g. fosstodon.org',
    account_acct LowCardinality(String) COMMENT 'Mastodon account acct, e.g. R_Foundation',
    account_id String COMMENT 'Mastodon account ID as opaque string; never cast to integer',
    status_id String COMMENT 'Mastodon status ID as opaque string; never cast to integer',
    status_uri String COMMENT 'Federated Mastodon status URI',
    status_url String COMMENT 'Public HTML URL of the Mastodon status',
    status_created_at DateTime64(3, 'Asia/Seoul') COMMENT 'Mastodon status created_at normalized to Asia/Seoul; leading ORDER BY column for TB-scale pruning',
    status_edited_at Nullable(DateTime64(3, 'Asia/Seoul')) COMMENT 'Mastodon edited_at normalized to Asia/Seoul; NULL when the status has not been edited',
    visibility LowCardinality(String) COMMENT 'Mastodon visibility value such as public/unlisted/private/direct; crawler stores public-visible data only',
    language LowCardinality(String) COMMENT 'Mastodon language code; empty string when Mastodon returns null',
    language_code LowCardinality(String) DEFAULT 'en' COMMENT 'BCP-47 language code of raw Mastodon text; R Foundation source rows are en',
    sensitive UInt8 COMMENT '0=not sensitive, 1=sensitive flag returned by Mastodon API',
    spoiler_text String COMMENT 'Mastodon content warning/spoiler text; empty string when absent',
    content_html String COMMENT 'Mastodon sanitized HTML content returned by API; external raw content; SSOT 아님',
    content_text String COMMENT 'HTML-stripped text generated by crawler for search/display convenience; SSOT 아님',
    in_reply_to_id Nullable(String) COMMENT 'Parent Mastodon status ID as opaque string when this status is a reply',
    in_reply_to_account_id Nullable(String) COMMENT 'Parent Mastodon account ID as opaque string when this status is a reply',
    is_reblog UInt8 COMMENT '0=original/reply status wrapper, 1=reblog wrapper status',
    reblog_status_id Nullable(String) COMMENT 'Reblogged Mastodon status ID as opaque string when is_reblog=1',
    replies_count UInt32 COMMENT 'Reply count returned by Mastodon API at crawl time',
    reblogs_count UInt32 COMMENT 'Reblog count returned by Mastodon API at crawl time',
    favourites_count UInt32 COMMENT 'Favourite count returned by Mastodon API at crawl time',
    active UInt8 COMMENT '1=available in latest crawler observation, 0=tombstone/deleted-or-missing marker produced by full backfill comparison',

    tags_json String COMMENT 'Mastodon tags array JSON string from raw status payload',
    mentions_json String COMMENT 'Mastodon mentions array JSON string from raw status payload',
    emojis_json String COMMENT 'Mastodon emojis array JSON string from raw status payload',
    media_attachments_json String COMMENT 'Mastodon media_attachments array JSON string; image attachments include image_base64/data_uri/image_sha256 when crawler downloaded them',
    card_json String COMMENT 'Mastodon preview card JSON string; empty object when absent',
    poll_json String COMMENT 'Mastodon poll JSON string; empty object when absent',
    raw_status_json String COMMENT 'Normalized full Mastodon Status JSON string including base64 image attachment fields; OLAP raw cache; SSOT 아님',
    payload_hash UInt64 COMMENT 'Stable UInt64 hash of normalized raw_status_json and tombstone state for change detection',
    image_count UInt8 COMMENT 'Number of image media attachments observed in the status',
    image_base64_count UInt8 COMMENT 'Number of image media attachments successfully downloaded and embedded as base64 by crawler',
    has_image_base64 UInt8 COMMENT '0=no embedded base64 image, 1=at least one image attachment embedded as base64',

    fetched_at DateTime64(3, 'Asia/Seoul') COMMENT 'Crawler fetch timestamp in Asia/Seoul',
    created_at DateTime64(3, 'Asia/Seoul') COMMENT 'Kafka producer event creation timestamp in Asia/Seoul',
    ingested_at DateTime64(3, 'Asia/Seoul') DEFAULT now64(3, 'Asia/Seoul') COMMENT 'ClickHouse ingestion timestamp in Asia/Seoul',
    kafka_topic LowCardinality(String) COMMENT 'Kafka topic lineage, normally webr.events',
    kafka_partition UInt32 COMMENT 'Kafka partition lineage',
    kafka_offset UInt64 COMMENT 'Kafka offset lineage'
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/Data_R_Project_Mastodon_Raw/raw_local', '{replica}')
PARTITION BY toYYYYMM(status_created_at)
ORDER BY (status_created_at, instance_host, account_acct, status_id, uuid)
SETTINGS index_granularity = 8192
COMMENT 'Mastodon public account raw status snapshots local replicated table; raw crawler data lands here first; OLAP 전용; SSOT 아님; TB 확장 전제';
