#!/usr/bin/env python3
"""Record the latest Web-R content CDN commit in ClickHouse."""

from __future__ import annotations

import argparse
import base64
import hashlib
import http.client
import json
import os
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime
from pathlib import Path
from typing import Any

from clickhouse_http import build_clickhouse_url
from export_r_ecosystem_cdn import (
    clickhouse_error_category,
    env_bool,
    is_transient_clickhouse_export_failure,
)


DEFAULT_REPO = "statground/web-r_CDN2_contents"
DEFAULT_BRANCH = "main"
DEFAULT_SCOPE = "web-r-content"
DEFAULT_LANGUAGE = "ko"
RELEASE_LOG_TABLE = "Data_R_Community_Service.web_r_cdn_release_log"
DEFAULT_RECORD_ATTEMPTS = 3
MAX_RECORD_ATTEMPTS = 6
DEFAULT_RECORD_BACKOFF_SECONDS = 2.0
MAX_RECORD_BACKOFF_SECONDS = 30.0


class ClickHouseReleaseRecordError(RuntimeError):
    def __init__(self, status_code: int, category: str, detail: str = "") -> None:
        self.status_code = int(status_code or 0)
        self.category = clickhouse_error_category(category or detail)
        self.detail = detail
        super().__init__(str(self))

    def __str__(self) -> str:
        if self.status_code:
            return f"ClickHouse release record insert failed: HTTP {self.status_code} {self.category}"
        return f"ClickHouse release record insert failed: {self.category}"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--report", required=True, help="JSON report generated by the CDN export workflow step")
    parser.add_argument("--commit-sha", required=True, help="CDN commit SHA that contains the exported content")
    parser.add_argument("--repo", default=DEFAULT_REPO)
    parser.add_argument("--branch", default=DEFAULT_BRANCH)
    parser.add_argument("--scope", default=DEFAULT_SCOPE)
    parser.add_argument("--language", default=DEFAULT_LANGUAGE)
    args = parser.parse_args()

    commit_sha = normalize_sha(args.commit_sha)
    if not commit_sha:
        raise SystemExit("valid CDN commit SHA is required")

    report_path = Path(args.report)
    report = json.loads(report_path.read_text(encoding="utf-8")) if report_path.exists() else {}
    manifest_paths = report.get("manifest_paths") or ["contents/ko/index.json", "packages/ko/index.json", "community/ko/index.json"]
    item_count = report_item_count(report)
    published_at = datetime.now().astimezone().strftime("%Y-%m-%d %H:%M:%S.%f")[:-3]
    version = int(time.time() * 1000)
    base_url = f"https://cdn.jsdelivr.net/gh/{args.repo}@{commit_sha}"
    release_id = f"{args.scope}:{args.language}:{commit_sha}"
    payload = {
        "release_id": release_id,
        "release_scope": args.scope,
        "language": args.language,
        "cdn_repo": args.repo,
        "cdn_branch": args.branch,
        "commit_sha": commit_sha,
        "base_url": base_url,
        "manifest_paths_json": json.dumps(manifest_paths, ensure_ascii=False, separators=(",", ":")),
        "item_count": item_count,
        "payload_json": json.dumps(report, ensure_ascii=False, separators=(",", ":")),
        "published_at": published_at,
        "active": 1,
        "version": version,
    }
    attempts = bounded_int_env(
        "WEB_R_CDN_RELEASE_RECORD_ATTEMPTS",
        DEFAULT_RECORD_ATTEMPTS,
        minimum=1,
        maximum=MAX_RECORD_ATTEMPTS,
    )
    backoff_seconds = bounded_float_env(
        "WEB_R_CDN_RELEASE_RECORD_BACKOFF_SECONDS",
        DEFAULT_RECORD_BACKOFF_SECONDS,
        minimum=0.0,
        maximum=MAX_RECORD_BACKOFF_SECONDS,
    )

    try:
        attempts_used = insert_release_with_retry(
            RELEASE_LOG_TABLE,
            payload,
            scope=args.scope,
            attempts=attempts,
            backoff_seconds=backoff_seconds,
        )
    except ClickHouseReleaseRecordError as exc:
        if env_bool(os.environ, "WEB_R_CDN_RELEASE_RECORD_TRANSIENT_FAIL_OPEN", True) and is_transient_clickhouse_export_failure(exc.status_code, exc.category, exc.detail):
            print(
                f"[warn] Web-R CDN release record deferred scope={args.scope} "
                f"reason={exc.category} attempts={attempts}",
                file=sys.stderr,
            )
            print(
                json.dumps(
                    {
                        "release_id": release_id,
                        "commit_sha": commit_sha,
                        "item_count": item_count,
                        "record_deferred": True,
                        "deferred_reason": exc.category,
                        "deferred_http_status": exc.status_code,
                        "record_attempts": attempts,
                    },
                    ensure_ascii=False,
                )
            )
            return 0
        raise SystemExit(str(exc)) from exc
    print(
        json.dumps(
            {
                "release_id": release_id,
                "commit_sha": commit_sha,
                "item_count": item_count,
                "record_deferred": False,
                "record_attempts": attempts_used,
            },
            ensure_ascii=False,
        )
    )
    return 0


def normalize_sha(value: str) -> str:
    value = (value or "").strip().lower()
    if len(value) < 7 or len(value) > 40:
        return ""
    if not all(ch in "0123456789abcdef" for ch in value):
        return ""
    return value


def report_item_count(report: dict[str, Any]) -> int:
    explicit = int(report.get("item_count") or 0)
    if explicit > 0:
        return explicit
    total = 0
    for key in ("r_ecosystem_export", "r_package_export", "community_export", "workshop_export", "export", "packages", "news", "package_details"):
        total += int(report.get(key) or 0)
    return total


def insert_release_with_retry(
    table: str,
    row: dict[str, Any],
    *,
    scope: str,
    attempts: int,
    backoff_seconds: float,
) -> int:
    bounded_attempts = max(1, min(MAX_RECORD_ATTEMPTS, int(attempts)))
    bounded_backoff = max(0.0, min(MAX_RECORD_BACKOFF_SECONDS, float(backoff_seconds)))
    deduplication_token = release_record_deduplication_token(str(row.get("release_id") or ""))
    for attempt in range(1, bounded_attempts + 1):
        try:
            insert_json_each_row(
                table,
                row,
                deduplication_token=deduplication_token,
            )
            return attempt
        except ClickHouseReleaseRecordError as exc:
            transient = is_transient_clickhouse_export_failure(
                exc.status_code,
                exc.category,
                exc.detail,
            )
            if not transient or attempt >= bounded_attempts:
                raise
            print(
                f"[warn] Web-R CDN release record retry scope={scope} "
                f"reason={exc.category} attempt={attempt}/{bounded_attempts}",
                file=sys.stderr,
            )
            delay = min(MAX_RECORD_BACKOFF_SECONDS, bounded_backoff * attempt)
            if delay > 0:
                time.sleep(delay)
    raise AssertionError("unreachable release record retry state")


def release_record_deduplication_token(release_id: str) -> str:
    release_id = str(release_id or "").strip()
    if not release_id:
        raise ValueError("release_id is required for ClickHouse insert deduplication")
    return hashlib.sha256(f"web-r-cdn-release:v1:{release_id}".encode("utf-8")).hexdigest()


def insert_json_each_row(
    table: str,
    row: dict[str, Any],
    *,
    deduplication_token: str,
) -> None:
    token = str(deduplication_token or "").strip().lower()
    if len(token) != 64 or not all(character in "0123456789abcdef" for character in token):
        raise ValueError("valid SHA-256 ClickHouse insert deduplication token is required")
    row_json = json.dumps(
        row,
        ensure_ascii=False,
        separators=(",", ":"),
        sort_keys=True,
    )
    sql = (
        f"INSERT INTO {table} SETTINGS insert_deduplicate = 1, "
        f"insert_deduplication_token = '{token}' FORMAT JSONEachRow\n"
        f"{row_json}\n"
    )
    request = urllib.request.Request(clickhouse_url(), data=sql.encode("utf-8"), method="POST")
    user = first_env("CH_USER", "CLICKHOUSE_USER")
    password = first_env("CH_PASSWORD", "CLICKHOUSE_PASSWORD")
    if not user:
        raise SystemExit("ClickHouse user secret is required")
    request.add_header("Authorization", "Basic " + base64.b64encode(f"{user}:{password}".encode("utf-8")).decode("ascii"))
    request.add_header("Content-Type", "text/plain; charset=utf-8")
    try:
        with urllib.request.urlopen(request, timeout=int(os.environ.get("WEB_R_CDN_RELEASE_RECORD_HTTP_TIMEOUT", "45"))) as response:
            response.read()
    except urllib.error.HTTPError as exc:
        detail = exc.read(800).decode("utf-8", errors="replace")
        raise ClickHouseReleaseRecordError(exc.code, clickhouse_error_category(detail), detail) from exc
    except urllib.error.URLError as exc:
        raise ClickHouseReleaseRecordError(0, "CLICKHOUSE_NETWORK", str(exc)) from exc
    except http.client.IncompleteRead as exc:
        raise ClickHouseReleaseRecordError(0, "INCOMPLETE_READ", str(exc)) from exc
    except http.client.HTTPException as exc:
        raise ClickHouseReleaseRecordError(0, "HTTP_CLIENT_ERROR", str(exc)) from exc
    except TimeoutError as exc:
        raise ClickHouseReleaseRecordError(0, "TIMEOUT_EXCEEDED", str(exc)) from exc
    except OSError as exc:
        raise ClickHouseReleaseRecordError(0, "CLICKHOUSE_NETWORK", str(exc)) from exc


def clickhouse_url() -> str:
    try:
        return build_clickhouse_url(
            os.environ,
            default_format="JSONEachRow",
            max_execution_time=os.environ.get("WEB_R_CDN_RELEASE_RECORD_CH_MAX_EXECUTION_TIME", "45"),
            max_threads=os.environ.get("WEB_R_CDN_RELEASE_RECORD_CH_MAX_THREADS", "1"),
        )
    except RuntimeError as exc:
        raise SystemExit(str(exc)) from exc


def first_env(*keys: str) -> str:
    for key in keys:
        value = os.environ.get(key, "").strip()
        if value:
            return value
    return ""


def bounded_int_env(
    key: str,
    default: int,
    *,
    minimum: int,
    maximum: int,
) -> int:
    raw = os.environ.get(key, "").strip()
    try:
        value = int(raw) if raw else int(default)
    except ValueError as exc:
        raise SystemExit(f"{key} must be an integer") from exc
    return max(int(minimum), min(int(maximum), value))


def bounded_float_env(
    key: str,
    default: float,
    *,
    minimum: float,
    maximum: float,
) -> float:
    raw = os.environ.get(key, "").strip()
    try:
        value = float(raw) if raw else float(default)
    except ValueError as exc:
        raise SystemExit(f"{key} must be a number") from exc
    return max(float(minimum), min(float(maximum), value))


def redact_detail(value: str) -> str:
    value = value.replace(first_env("CH_PASSWORD", "CLICKHOUSE_PASSWORD"), "***") if first_env("CH_PASSWORD", "CLICKHOUSE_PASSWORD") else value
    hosts = [first_env("CH_HOST", "CLICKHOUSE_HOST")]
    for key in ("CH_URL", "CLICKHOUSE_URL", "CLICKHOUSE_HTTP_URL"):
        raw = os.environ.get(key, "").strip()
        if not raw:
            continue
        try:
            parsed = urllib.parse.urlsplit(raw)
            hosts.extend([parsed.netloc, parsed.hostname or ""])
        except ValueError:
            hosts.append(raw)
    for host in hosts:
        host = host.strip()
        if not host:
            continue
        value = value.replace(host, "<clickhouse-host>")
    return value


if __name__ == "__main__":
    sys.exit(main())
