#!/usr/bin/env python3
"""Record the latest Web-R content CDN commit in ClickHouse."""

from __future__ import annotations

import argparse
import base64
import json
import os
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime
from pathlib import Path
from typing import Any

from clickhouse_http import build_clickhouse_url


DEFAULT_REPO = "statground/web-r_CDN2_contents"
DEFAULT_BRANCH = "main"
DEFAULT_SCOPE = "web-r-content"
DEFAULT_LANGUAGE = "ko"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--report", required=True, help="JSON report generated by the CDN export workflow step")
    parser.add_argument("--commit-sha", required=True, help="CDN commit SHA that contains the exported content")
    parser.add_argument("--repo", default=DEFAULT_REPO)
    parser.add_argument("--branch", default=DEFAULT_BRANCH)
    parser.add_argument("--scope", default=DEFAULT_SCOPE)
    parser.add_argument("--language", default=DEFAULT_LANGUAGE)
    args = parser.parse_args()

    commit_sha = normalize_sha(args.commit_sha)
    if not commit_sha:
        raise SystemExit("valid CDN commit SHA is required")

    report_path = Path(args.report)
    report = json.loads(report_path.read_text(encoding="utf-8")) if report_path.exists() else {}
    manifest_paths = report.get("manifest_paths") or ["contents/ko/index.json", "packages/ko/index.json", "community/ko/index.json"]
    item_count = report_item_count(report)
    published_at = datetime.now().astimezone().strftime("%Y-%m-%d %H:%M:%S.%f")[:-3]
    version = int(time.time() * 1000)
    base_url = f"https://cdn.jsdelivr.net/gh/{args.repo}@{commit_sha}"
    release_id = f"{args.scope}:{args.language}:{commit_sha}"
    payload = {
        "release_id": release_id,
        "release_scope": args.scope,
        "language": args.language,
        "cdn_repo": args.repo,
        "cdn_branch": args.branch,
        "commit_sha": commit_sha,
        "base_url": base_url,
        "manifest_paths_json": json.dumps(manifest_paths, ensure_ascii=False, separators=(",", ":")),
        "item_count": item_count,
        "payload_json": json.dumps(report, ensure_ascii=False, separators=(",", ":")),
        "published_at": published_at,
        "active": 1,
        "version": version,
    }

    insert_json_each_row("Data_R_Community_Service.web_r_cdn_release_log", payload)
    print(json.dumps({"release_id": release_id, "commit_sha": commit_sha, "item_count": item_count}, ensure_ascii=False))
    return 0


def normalize_sha(value: str) -> str:
    value = (value or "").strip().lower()
    if len(value) < 7 or len(value) > 40:
        return ""
    if not all(ch in "0123456789abcdef" for ch in value):
        return ""
    return value


def report_item_count(report: dict[str, Any]) -> int:
    explicit = int(report.get("item_count") or 0)
    if explicit > 0:
        return explicit
    total = 0
    for key in ("r_ecosystem_export", "r_package_export", "community_export", "export", "packages", "news", "package_details"):
        total += int(report.get(key) or 0)
    return total


def insert_json_each_row(table: str, row: dict[str, Any]) -> None:
    sql = f"INSERT INTO {table} FORMAT JSONEachRow\n" + json.dumps(row, ensure_ascii=False, separators=(",", ":")) + "\n"
    request = urllib.request.Request(clickhouse_url(), data=sql.encode("utf-8"), method="POST")
    user = first_env("CH_USER", "CLICKHOUSE_USER")
    password = first_env("CH_PASSWORD", "CLICKHOUSE_PASSWORD")
    if not user:
        raise SystemExit("ClickHouse user secret is required")
    request.add_header("Authorization", "Basic " + base64.b64encode(f"{user}:{password}".encode("utf-8")).decode("ascii"))
    request.add_header("Content-Type", "text/plain; charset=utf-8")
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            response.read()
    except urllib.error.HTTPError as exc:
        detail = exc.read(300).decode("utf-8", errors="replace")
        raise SystemExit(f"ClickHouse release record insert failed: HTTP {exc.code}: {redact_detail(detail)}") from exc
    except urllib.error.URLError as exc:
        raise SystemExit(f"ClickHouse release record insert failed: {exc.__class__.__name__}") from exc


def clickhouse_url() -> str:
    try:
        return build_clickhouse_url(os.environ, default_format="JSONEachRow", max_execution_time="30")
    except RuntimeError as exc:
        raise SystemExit(str(exc)) from exc


def first_env(*keys: str) -> str:
    for key in keys:
        value = os.environ.get(key, "").strip()
        if value:
            return value
    return ""


def redact_detail(value: str) -> str:
    value = value.replace(first_env("CH_PASSWORD", "CLICKHOUSE_PASSWORD"), "***") if first_env("CH_PASSWORD", "CLICKHOUSE_PASSWORD") else value
    hosts = [first_env("CH_HOST", "CLICKHOUSE_HOST")]
    for key in ("CH_URL", "CLICKHOUSE_URL", "CLICKHOUSE_HTTP_URL"):
        raw = os.environ.get(key, "").strip()
        if not raw:
            continue
        try:
            parsed = urllib.parse.urlsplit(raw)
            hosts.extend([parsed.netloc, parsed.hostname or ""])
        except ValueError:
            hosts.append(raw)
    for host in hosts:
        host = host.strip()
        if not host:
            continue
        value = value.replace(host, "<clickhouse-host>")
    return value


if __name__ == "__main__":
    sys.exit(main())
